# Generated by Django 2.0.2 on 2018-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.IntegerField()),
                ('solidity', models.IntegerField()),
                ('datecode', models.CharField(max_length=9)),
            ],
        ),
    ]
