# Generated by Django 2.0.2 on 2018-07-07 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutlife_app', '0002_auto_20180706_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmlog',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 7, 7, 9, 2, 16, 644393)),
        ),
    ]
