# Generated by Django 2.0.2 on 2018-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutlife_app', '0011_auto_20180707_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmlog',
            name='time',
            field=models.CharField(default='00:00', max_length=5),
            preserve_default=False,
        ),
    ]
